### ISSUE TITLE
BUG - Local Audio / Video not working in RN 0.73.2

### ISSUE THREAD

**Issue by Bowlerr** [daily-co/react-native-daily-js#47] opened 2024-01-10 15:16 UTC
# Expected behavior

When joining a call, I expect to get the local audio and video.

# Describe the bug (unexpected behavior)

Since Updating to 0.73.2, Local audio and video has stopped working.

`tracks {"audio": {"off": {"byUser": true}, "persistentTrack": undefined, "state": "off"}, "screenAudio": {"off": {"byUser": true}, "persistentTrack": null, "state": "off"}, "screenVideo": {"off": {"byUser": true}, "persistentTrack": null, "state": "off"}, "video": {"off": {"byUser": true}, "persistentTrack": undefined, "state": "off"}}`

The reason seems to be `byUser` but nothing has changed in my code.

Tested on both Android and iOS.

# Steps to reproduce

Join call.

# System information 

* Device: Samsung Galaxy S21+ Also iOS
* OS, version: Android: 13 Also iOS

**Comment by vipyne** [comment] 2024-01-26 20:12
@Bowlerr could the room or domain configuration have changed?  those track objects look like what it would be if `start_audio_off` and `start_video_off` were set to `true`.  (room config docs [here](https://docs.daily.co/reference/rest-api/rooms/set-room-config#start_audio_off))

**Comment by filipi87** [comment] 2024-02-28 12:41
Since we are unable to reproduce it and haven't received further feedback, we are closing this issue for now. Feel free to create a new one in case you are still facing it.

**Closed as completed by filipi87** 2024-02-28 12:41 UTC
Labels: bug
