### ISSUE TITLE
Android App crashes on join call method

### ISSUE THREAD

**Issue by vineetk242000** [daily-co/react-native-daily-js#31] opened 2022-09-21 20:42 UTC
# Expected behavior
The daily-js should work fine on android just like the iOS.

# Describe the bug (unexpected behavior)

The daily-js sdk is working perfectly fine for iOS but in Android, once the join method is called the console keeps repeating this log  "unrecognised iframe message join-meeting", and the app freezes after this step. It is happening with or without attaching event listeners to my call object. 

# Steps to reproduce
Set your project environment as described below.
Run on any android device on simulator
Try to join a call
App freezes with the join method logging "unrecognised iframe message join-meeting" repeatedly

# Screenshots
![carbon](https://user-images.githubusercontent.com/57609127/191604167-48a9d169-1ef4-4c7e-b0f6-f77ba22f4ccb.png)

# System information 

* Device: Pixel 4A simulator or any physical device
* OS, version:  Android 12

# Additional context

My dependencies of the project are as follows:
react-native : "0.63.4"
react: "16.13.1"
@daily-co/react-native-daily-js: "0.29.0" (tried previous versions still the same issue)
@daily-co/react-native-webrtc : "1.94.1-daily.5"

Android gradle:
buildToolsVersion = "30.0.2"
 minSdkVersion = 24
 compileSdkVersion =31
 targetSdkVersion = 30

**Comment by filipi87** [comment] 2022-09-23 18:44
Hi @vineetk242000 , I tried to reproduce the issue here, but without success.

The main difference is, I was using the version 0.69 from react-native, instead of the version 0.63.

We have validated that our library is working on Android 12 with the versions 0.66, 0.68 and 0.69 of react native on our playground app. We have not tested with version 0.67 but should also work without any issue.

The version 0.66 was the first one release which react native has announced Android 12, as you can see here: https://reactnative.dev/blog/2021/10/01/version-066

Another important thing to consider, is that on Android 12, react native has a current open issue of intermittent crash A/libc: https://github.com/facebook/react-native/issues/33124
To workaround this issue, we have migrated our playground app to use Hermes. Since then, the crash issue has not happened anymore.

Could you test with our playground app and see if you are able to reproduce the issue ?

https://github.com/daily-co/react-native-daily-js-playground

**Comment by vineetk242000** [comment] 2022-09-26 08:45
Hi @filipi87, I tried the playground app and even the party-line. It is working perfectly fine in my environment on Android. Could you confirm if there is any issue with the react native version 0.63  for this daily-js integration on Android ?

**Comment by filipi87** [comment] 2022-10-11 11:50
Hi @vineetk242000 ,

Sorry for the late reply, I was out the last couple of weeks.

We currently don't have any known issue with the version 0.63 of react-native, but since It is a really old version of react native and they recommend using at least the version 0.66 for Android 12, we don't usually execute tests using this version. I would need to execute a regression test over this version, to see if we are going to face the same issue.

Have you considered updating the app to a more recent version of react native, and migrate It to use Hermes (as I have mentioned above, this is a known issue between react native and Android 12) ?

Please let me know if that is an option.

**Comment by filipi87** [comment] 2022-11-04 10:24
Closing this issue, since we are unable to reproduce on the latest versions of react native.

**Closed as completed by filipi87** 2022-11-04 10:24 UTC
Labels: bug

**Comment by vineetk242000** [comment] 2022-11-11 17:41
Hey @filipi87,
I was working on some other features for my app and just now came back to dailyjs integration. My application was already using hermes on android. When I tried joining a call with hermes disabled on android then it worked with my current react native version.  So, Dailyjs is working fine now with with my app on android. I just wanted to know, will this create some issue going forward  as this scenario is a bit contrasting in comparison to docs.

**Comment by filipi87** [comment] 2022-11-18 20:27
Hi @vineetk242000 

That open react native issue of intermittent crash A/libc for Android 12, has been open for the version `0.66` of react native: https://github.com/facebook/react-native/issues/33124

Considering that you are using version `0.63`, maybe that is why you are not experiencing this issue without using Hermes, but I can't be totally sure. 

On the version 0.70 of react native, Hermes is now the default engine: https://reactnative.dev/blog/2022/09/05/version-070.  

So now, if you decide to keep your current version, I would just recommend trying to test a lot on Android 12, to see if you will face any intermittent crashes. 

And it would be nice to already plan to update to the latest version of react native which already comes with Hermes enabled and we are sure that is working fine.
