### ISSUE TITLE
Pod install conflicting names

### ISSUE THREAD

**Issue by rjuevesano** [daily-co/react-native-daily-js#44] opened 2023-08-22 23:17 UTC
After running `npx pod-install` and I got this error

```
Installing JitsiWebRTC (111.0.2)
Installing react-native-webrtc (111.0.0-daily.1)
[!] The 'Pods-Project' target has frameworks with conflicting names: webrtc.xcframework.
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: The 'Pods-Project' target has frameworks with conflicting names: webrtc.xcframework.
```

```
"react": "18.2.0",
"react-native": "^0.71.8"
```

**Comment by filipi87** [comment] 2024-01-29 14:29
Hi @rjuevesano,

If you remove `node_modules` and `ios/Pods`, and install the dependencies again, `npm i` and `npx pod-install`, are you still able to reproduce the issue ?

**Comment by filipi87** [comment] 2024-02-28 12:43
Since we are unable to reproduce it and haven't received further feedback, we are closing this issue for now. Feel free to create a new one in case you are still facing it.

**Closed as completed by filipi87** 2024-02-28 12:43 UTC
Labels: bug
