### ISSUE TITLE
BUG - Type Missing For DailyStreamingCustomLayoutConfig

### ISSUE THREAD

**Issue by thorbenprimke** [daily-co/react-native-daily-js#26] opened 2022-06-19 18:45 UTC
# Expected behavior

A type for the preset with value `custom` is missing. 

# Describe the bug (unexpected behavior)

Type would be present. 

# Steps to reproduce

Make a call to `startLiveStreaming` or `updateLiveStreaming` and see type exception.

# System information 

Lib: 0.25.0

# Additional context

Since the compositionId could be a truly custom value in the future, maybe `composition_params` has to be to be a generic type to ensure type safely (down the road).

**Comment by filipi87** [comment] 2022-07-04 19:40
Just to give you some feedback, we have already fixed It and have an open PR. It will probably be merged before our next release.

**Comment by filipi87** [comment] 2022-07-06 16:07
Hi, just to give you an update, the fix has already been merged and will be available on the next release, 0.26.0.

**Comment by filipi87** [comment] 2022-08-01 13:53
The issue is available on the version `0.27.0`.

**Closed by filipi87** 2022-08-01 13:53 UTC
Labels: bug
