### ISSUE TITLE
Android app crashing as soon as it launches

### ISSUE THREAD

**Issue by MilindKudale** [daily-co/react-native-daily-js#51] opened 2024-03-12 11:26 UTC
java.lang.RuntimeException: Unable to get provider com.reactnativecommunity.webview.RNCWebViewFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.reactnativecommunity.webview.RNCWebViewFileProvider" on path: DexPathList[[zip file "/data/app/~~l-Ngh-WdT4fHay_-X0CNIw==/com.healthcareapp-LPohXkgBruAB0YAgzJvMRg==/base.apk"],nativeLibraryDirectories=[/data/app/~~l-Ngh-WdT4fHay_-X0CNIw==/com.healthcareapp-LPohXkgBruAB0YAgzJvMRg==/lib/arm64, /data/app/~~l-Ngh-WdT4fHay_-X0CNIw==/com.healthcareapp-LPohXkgBruAB0YAgzJvMRg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]

React native version 0.63.4
OS : Android

**Comment by filipi87** [comment] 2024-03-15 12:12
Hi @MilindKudale,

Looking at the logs above, it seems like you are attempting to execute it inside a webview, is that correct? If so, that is probably the issue, as `react-native-daily-js` is not intended to be executed within a webview.

Additionally, I noticed that you are using a relatively old version of React Native. You might consider upgrading to a more recent version that is still supported.

Could you try reproducing the issue using our demo app? You can find it [here](https://github.com/daily-co/react-native-daily-js-playground). If you're able to replicate the issue, please provide detailed steps to reproduce it. If not, please share a code snippet with more information on how to reproduce it.

Some additional information that would be helpful:

Version of `react-native-daily-js`.
Whether the issue occurs on Android or iOS, and which version.

**Comment by filipi87** [comment] 2024-03-22 18:00
Closing this issue since we don't have enough information to try to reproduce it. Feel free to open a new one providing the information requested above in case you are still facing the issue.

**Closed as completed by filipi87** 2024-03-22 18:00 UTC
Labels: bug
